Alterando CICD

diff --git a/.github/workflows/github-cicd.yml b/.github/workflows/github-cicd.yml
--- a/.github/workflows/github-cicd.yml
+++ b/.github/workflows/github-cicd.yml
@@ -6,20 +6,28 @@ on:
       - published  # Aciona quando um release é publicado
 
 jobs:
-  build:
+  check-tag:
     runs-on: ubuntu-latest
-
+    outputs:
+      tag: ${{ steps.tag-check.outputs.tag }}
     steps:
-      # Etapa para fazer o checkout do repositório
-      - name: Check out the repository
+      - name: Check out code
         uses: actions/checkout@v3
-        with:
-          fetch-depth: 0  # Garante que o repositório seja clonado com todas as tags e histórico
-
-      # Usa o nome da release para construir a tag
-      - name: Set tag from release name
-        run: echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
-
+      
+      - name: Check for tag
+        id: tag-check
+        run: |
+          TAG_NAME=${{ github.event.release.tag_name }}
+          if [ -z "$TAG_NAME" ]; then
+            echo "::error::No tag found on this commit."
+            exit 1
+          fi
+          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
+          
+  build-and-push:
+    needs: check-tag
+    steps:
+    runs-on: ubuntu-latest
       # Configura o Docker Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -33,13 +41,13 @@ jobs:
 
       # Mostra o nome da release para verificar
       - name: Show release name
-        run: echo "feliperibeiro95/linux101-web:$TAG_NAME"
+        run: echo "feliperibeiro95/linux101-web:${{ needs.check-tag.outputs.tag }}"
 
       # Construção e envio para o Docker Hub
       - name: Build and push
         uses: docker/build-push-action@v2
         with:
           push: true
-          tags: feliperibeiro95/linux101-web:latest
+          tags: feliperibeiro95/linux101-web:${{ needs.check-tag.outputs.tag }}
           context: ./linux101-web
           platforms: linux/amd64,linux/arm64
